### ISSUE TITLE
Txin commit error: pq: Unknown tx_id:prevout_n combination: 648538036:1

### ISSUE THREAD

**Issue by xiaoqge** [blkchain/blkchain#9]
@grisha 
When my database restarts unexpectedly, some txid will be lost in the startup program, and the following error will be found in the log. How can I fix this problem, thank you very much
```
2021/06/12 00:53:03 Txin commit error: pq: Unknown tx_id:prevout_n combination: 648538036:1
2021/06/12 00:53:05 Txin commit error: pq: Unknown tx_id:prevout_n combination: 648537969:0
2021/06/12 00:53:06 Txin commit error: pq: Unknown tx_id:prevout_n combination: 648533578:0
```

**Comment by grisha** [comment]
I've seen this happen when somehow you miss a block, and the 0ae4897 commit was supposed to fix this. 

There is no easy fix to this missing block situation once you have the database in this state, which is why I highly recommend keeping it in ZFS and taking periodic snapshots, so that you could revert to some previously known good state and not have to repopulate the entire database from scratch again.

**Comment by xiaoqge** [comment]
Thank you very much, I can only sync from the beginning, right?

**Comment by grisha** [comment]
Yes, sorry. 

Alternatively, but "your mileage may vary", I suppose you could just manually DELETE the latest blocks and associated txs, inputs and outputs, etc, and may be it will just catch up correctly. I'd try that first before blowing it away.

**Comment by grisha** [comment]
That looks like a bug!

https://github.com/blkchain/blkchain/blob/0ae4897792cb095d63a7411e9227f988612d70aa/db/postgres.go#L1321

Should be `OLD.prevout_tx_id` instead of just `prevout_tx_id`.

I'll push a fix, but since this is a trigger function in Postgres that is only created once, to fix it without blowing away the DB you should rerun the `CREATE OR REPLACE FUNCTION ...` (at line 1316) manually.

**Comment by xiaoqge** [comment]
Thanks, I tried to delete the latest missing block and re-synchronize, but some data is still lost. I downloaded the latest code and restarted the synchronization. Try it
